R studio demo course
SDU-eScience/UCloud-Courses pull request #9
Opened 2024-09-02 09:29 UTC by Rymik19

This demo course is based on Duke University's Statistical Science Introductory Data Science courses: [DukeStatSci/introds](https://github.com/DukeStatSci/introds). 

It includes general instructions (*README.md*) to course creation and how this particular course was created. It contains a `build-and-run-course.py` which can be simply executed to build and test the R Studio image with imported course content. Additionally, it uses an initialization script and adds persistent files  (*/renv* and */slides*) to the `/work` directory that are accessible in different classes.

2024-11-04 13:33 UTC, JHavstein requested changes
I haven't reviewed the files i `renv/` and `slides/` since I assume that these originate from somewhere else. Let me know if I should have a look at these files also. 

@JHavstein They come from the course repository: https://github.com/jeselginAU/demo-r-studio-course/tree/main/renv 
I have tested that the Rmd files can be "Knitted" and that the `renv` environment is loaded using the `activate.R` to manage R package dependencies. -Rytis

_General changes:_ 

- The course code should be changed everywhere (in file names, folder names, and inside files) from `0000` to the AU actual course code.

@JHavstein  I believe this course is only supposed to be an example on how to set up a course, so there is no actual AU course code. -Rytis

@Rymik19 @jeselginAU OK, let's keep `0000` as the course code then. -Jonas 

- Likewise, the course release date should be changed from `2024-01-01` to the correct one, say `2024-01-09`.

_Testing:_ 

I've only tested locally so far. The image builds successfully with `docker-build.py` and the different classes can be launched correctly using `docker-run.py` and editing `START_COMMAND`. (The container won't run interactively, but I think this has to do with the base image.)

2024-11-11 14:46 UTC, JHavstein requested changes
If there are any files or folders that aren't used (`activate.R`?) they should be removed.

The course works on dev.

2024-12-30 10:06 UTC, Rymik19 commented
I have created a simple script `analysis.R` that uses `dataset.csv` to plot some data (Math scores) using `ggplot2` library for plotting and `dplyr` library for summarizing data. I have made it modular to feature functions and a main function. It prints out some statistics about the data and creates plots for distribution and density.

It is available at the course material repository [here](https://github.com/Rymik19/rStudioDemoCourse). 

The libraries are installed using an R environment. The environment files (`renv` folder, `.Rprofile` and `renv.lock`) are added in the Docker image at `/home/${USERID}/Renvironment`. At startup, they are then copied to `/work` and the environment is activated using `Rscript /work/Renvironment/renv/activate.R`.

@JHavstein and @emolinaro I would appreciate your feedback on this approach.

2025-01-08 08:53 UTC, JHavstein commented
> @JHavstein and @emolinaro I would appreciate your feedback on this approach.

@Rymik19 I'll review it as soon as possible.

2025-01-09 11:30 UTC, JHavstein requested changes
The course container works fine on dev. But the environment does not work seamlessly. 

I understand the general appeal of working inside a dedicated R environment, but I believe that the (simpler) solution of installing the required R packages from the Dockerfile (see review comments) makes more sense in this case. By installing R packages in this way we also avoid cluttering the `/work` folder, and the different course development scripts become easier to read which makes sense given that this is meant to be a demo course.

2025-01-09 11:30 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/Dockerfile
> +COPY --chown=${USERID}:${GROUPID} renv.lock /Renvironment/renv.lock
Remove the `renv`setup. 
```suggestion
```

2025-01-09 11:30 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/Dockerfile
> +WORKDIR /home/${USERID}
```suggestion
WORKDIR /tmp
```

2025-01-09 11:30 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/Dockerfile
> +
Install the required R packages directly from the Dockerfile like so. This removes the need for an R environment:
```suggestion
RUN sudo apt-get update -qq \
 && install2.r --error --deps TRUE \
    ggplot2 \
    dplyr \
 && rm -rf /tmp/downloaded_packages/ /tmp/*.rds \
 && sudo apt-get clean \
 && sudo rm -rf /var/lib/apt/lists/*
```
In fact, this step is not necessary since the entire `tidyverse` package suite is already installed into the base image. But I think it still could make sense to include the code above for teachers to see how to install R packages from a Dockerfile - although perhaps we should choose to install some package which is not pre-installed in the base image.

2025-01-09 11:30 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/.Rprofile
Can be deleted.

2025-01-09 11:30 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/renv.lock
Can be deleted.

2025-01-09 11:30 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/renv/activate.R
Can be deleted.

2025-01-09 11:30 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/renv/settings.json
Can be deleted.

2025-01-09 11:30 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/start_course.sh
> +echo "Environment successfully activated!"
```suggestion
```

2025-01-09 11:30 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/README.md
This README must be revised such that it only contains information which is relevant specifically for this course. As such, it can probably be kept pretty short. For general things about how to develop UCloud courses etc., teachers should read the repo's wiki.

@JHavstein I have updated the documentation. It borrows a few paragraphs from the NLP course README regarding machine and class selection, which could just be referenced. It highlights the scripts used in `class_01` and `class_02`, with the latter requiring package installation in the Dockerfile. /Rytis

2025-01-09 11:30 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/renv/.gitignore
Can be deleted.

2025-01-09 11:30 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/r-studio-demo-course__0000-app.yml
> +        value: "class_04"
As far as I can see, only `class_01` is available in the external repo. Is this intentional? If so, we should remove the other classes from here.

2025-01-09 11:30 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/start_course.sh
> +fi
```suggestion
fi

```

2025-01-10 12:25 UTC, Rymik19 commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/docker-run.py
@JHavstein I experienced some issues when testing the -it flag.

When setting INTERACTIVE_MODE = "True":

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...s6-chown: fatal: unable to chown /var/run/s6/etc/cont-init.d/02_userconf: Operation not permitted
s6-chown: fatal: unable to chown /var/run/s6/etc/cont-init.d/01_set_env: Operation not permitted
s6-chmod: fatal: unable to change mode of /var/run/s6/etc/cont-init.d/01_set_env: Operation not permitted
s6-chmod: fatal: unable to change mode of /var/run/s6/etc/cont-init.d/02_userconf: Operation not permitted
s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/rstudio/run: Operation not permitted
s6-chmod: fatal: unable to change mode of /var/run/s6/etc/services.d/rstudio/run: Operation not permitted
s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/rstudio/finish: Operation not permitted
s6-chmod: fatal: unable to change mode of /var/run/s6/etc/services.d/rstudio/finish: Operation not permitted
exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01_set_env: executing... 
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/01_set_env: Permission denied
[cont-init.d] 01_set_env: exited 127.
[cont-init.d] 02_userconf: executing... 
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/02_userconf: Permission denied
[cont-init.d] 02_userconf: exited 127.
[cont-init.d] done.
[services.d] starting services
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise rstudio: warning: unable to spawn ./run - waiting 10 seconds
[services.d] done.
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise rstudio: warning: unable to spawn ./run - waiting 10 seconds
^C[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.


Any ideas why this happens?

2025-01-10 12:39 UTC, Rymik19 commented
~~@JHavstein One other issue I am experiencing now is that the downloaded repository files are in the container at `/work/classes_01` however they do not appear in the RStudio interface. I do not know why, but perhaps there is an issue with my local setup. 
Could you verify that by testing if the downloaded repository files (`analysis.R` & `dataset.csv`) appear in R Studio?~~

@Rymik19 I'll do that first thing when I put a new version on dev for testing. Please let me know when the code is ready for a new iteration of testing. (/Jonas)

@JHavstein I have created a new `class_02` folder with a [script](https://github.com/Rymik19/rStudioDemoCourse/blob/main/classes/class_02/example_with_new_packages.R) that uses `janitor` and `plotly` packages. I have checked that these are not included in the base image. I have tested this locally with success. My issue above was tied with using WSL engine directly, instead of Docker Desktop when testing, which I solved.

2025-01-10 12:51 UTC, Rymik19 commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/r-studio-demo-course__0000-app.yml
> +        value: "class_04"
I have only created a script for one class, should I create another one for class_02 to facilitate class selection? I will remove the missing classes.

2025-01-10 12:54 UTC, Rymik19 commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/Dockerfile
> +
I will test the class script without installing the packages to confirm `tidyverse` is enough. I will then change the script to use other packages not included in the base image.

2025-01-10 12:54 UTC, Rymik19 commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/Dockerfile
> +WORKDIR /home/${USERID}
I think this command is not necessary.

2025-01-10 13:11 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/docker-run.py
I'll have to look more into it. But as far as I know, this is caused by the base image which is `rocker/rstudio` and not one of our own linux base images. As far as I can tell it has nothing to do with the scripts in this repo.

2025-01-10 13:17 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/Dockerfile
> +
OK. 

If you prepare a script for `class_02`, can you use a package in that script that is not present in the base image and then install the package from the Dockerfile? Just to demonstrate how this is done for people who will be using this course for inspiration.

2025-01-10 13:19 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/r-studio-demo-course__0000-app.yml
> +        value: "class_04"
Yes, please create one for `class_02` as well so that it will be possible to select between these class 1 and class 2. It can just be very simple script. When preparing the script, see also this comment: https://github.com/SDU-eScience/UCloud-Courses/pull/9#discussion_r1910366959 from above.

You can remove class 3 and 4 from the yaml file.

2025-01-16 08:46 UTC, JHavstein requested changes
The course works on UCloud - but see the comment to `start_course.sh`.

2025-01-16 08:46 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/README.md
> +This course serves as an example of setting up a course with `RStudio`.
```suggestion
This course is a demonstration of how to set up a simple UCloud course with `RStudio`.
```

2025-01-16 08:46 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/README.md
> +Choose the relevant class (module) from the dropdown menu in the UCloud job configuration interface.
```suggestion
Choose the relevant class (module) from the dropdown menu in the UCloud job submission page.
```

2025-01-16 08:46 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/README.md
> +The course materials (instructions and datasets) are hosted in a [GitHub](https://github.com/Rymik19/rStudioDemoCourse/tree/main/classes) repository.
```suggestion
The course materials (instructions and datasets) are hosted in an external [GitHub](https://github.com/Rymik19/rStudioDemoCourse/tree/main/classes) repository.
```

2025-01-16 08:46 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/README.md
> +The `analysis.R` script for `class_01` demonstrates data validation, group-wise summarization, and visualization using `ggplot2` which is already included in the base `RStudio` image.
```suggestion
The `analysis.R` script for `class_01` demonstrates data validation, group-wise summarization, and visualization using the `ggplot2` library.
```

2025-01-16 08:46 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/README.md
> +When the job is completed, the class_[module#] folder will be available in your UCloud drive inside the [Jobs](https://docs.cloud.sdu.dk/guide/monitoring.html#job-completed) folder.
```suggestion
When the job is completed, the `class_<module#>` folder will be available in your UCloud drive inside the [Jobs](https://docs.cloud.sdu.dk/guide/monitoring.html#job-completed) folder.
```

2025-01-16 08:46 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/README.md
> +By default, this parameter is set to `false` meaning the course materials are downloaded, except if a folder called `/work/class_[module#]` already exists.
```suggestion
By default, this optional parameter is set to `false` meaning the course materials are downloaded fro mthe external GitHub repository, except if a folder called `/work/class_[module#]` already exists.
```

2025-01-16 08:46 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/README.md
> +You can overwrite the existing folder by setting the option _Re-download course files_  to `true`. This will overwrite `/work/class_[module#]` inside the job and the mounted UCloud storage.
```suggestion
You can overwrite the existing folder by setting the option _Re-download course files_  to `true`. This will overwrite `/work/class_[module#]` with the current contents of the folder in the external GitHub repository.
```

2025-01-16 08:46 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/README.md
> +For information on how to use the _Initialization_ parameter, please refer to the [Initialization - Bash script](https://docs.cloud.sdu.dk/hands-on/init-sh.html), [Initialization - Conda packages](ht
This can be deleted since it's a general feature when submitting UCloud jobs.

```suggestion

```

2025-01-16 08:46 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/Dockerfile
> +
```suggestion

## Install required R libraries
```

2025-01-16 08:46 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/r-studio-demo-course__0000-app.yml
> +      If set to true, any existing files in your class folder will be overwritten.
To keep the description short.

```suggestion
      Re-download course materials from external repository (default: false). If set to true, the contents of mounted class folders for the selected class will be overwritten.
```

2025-01-16 08:46 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/README.md
> +You can select the machine type from the dropdown menu when configuring your UCloud job.
This can be deleted since it's a general thing when submitting jobs on UCloud.
```suggestion
```

2025-01-16 08:46 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/README.md
> +Once you start the course app, the course materials for the selected course module will be downloaded to the path `/work/class_[module#]`.
```suggestion
Once you start the course app, the course materials for the selected course module will be downloaded to the path `/work/class_<module#>`.
```

2025-01-16 08:46 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/README.md
> +files from the teachers GitHub repos won't be re-downloaded.
```suggestion
In other words, if you select class 1 and you mount a folder called `class_01` by using the parameter _Select folders to use_, files from the external GitHub repository won't be re-downloaded.
```

2025-01-16 08:46 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/README.md
> +You can overwrite the existing folder by setting the option _Re-download course files_  to `true`. This will overwrite `/work/class_[module#]` inside the job and the mounted UCloud storage.
```suggestion
You can overwrite the existing folder by setting the option _Re-download course files_  to `true`. This will overwrite `/work/class_<module#>` with the newest version of the relevant course materials from the external GitHub repository.
```

2025-01-16 08:46 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/start_course.sh
> +fi
This logic needs to be changed a bit. Specifically, it doesn't handle the case where a class module is selected, a class folder is mounted, and redownload is set to `false`. 

As I see it, the following cases must be handled:

1.  No class selected -> Start RStudio immediately
2. Class module selected AND no class folder mounted -> Download course materials from repo and start RStudio 
3. Class module selected AND a class folder mounted -> Download course materials according to redownload flag and start RStudio

I think the best way to do it would be to re-write the logic to first handle the above three cases and then move 
```
printf "\n==================="
printf "\n== Start RStudio ==\n"
printf "===================\n\n"
sudo /init  
```
out of the conditional statements to ensure that it's always started.

2025-01-20 12:51 UTC, Rymik19 commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/start_course.sh
> +fi
I have implemented this change. It is challenging for me to test locally the cases where a class folder is mounted, could you please ensure it is handled correctly?

2025-01-20 15:15 UTC, JHavstein commented on Courses/AU/r-studio-demo-course__0000/2024-09-01/start_course.sh
> +fi
Great - I'll be sure to test it.

I also just realized that `Class` is a mandatory parameter which defaults to `class_01`. This means that case 1 from my previous comment is not relevant after all. I'll just change this in the script (it is essentially just 2-3 lines that need to be deleted).

2025-01-20 15:41 UTC, JHavstein commented
@Rymik19: I observed the following: 

I selected a class, and mounted a class folder from a previous job where I had added some files that were not a part of the downloaded course material. Finally, I set the `re-download` flag to `true`. This resulted in the course files being re-downloaded, as expected. But the files I had added to the mounted course folder were still present after the re-download (i.e., along with the re-downloaded course material files). 

Is this the intended behavior? Or should the mounted course folder be wiped of content before the course files are redownload into the folder? 

_Follow-up:_ @Rymik19 If it's the intended behavior the section about the redownload flag in the `README` should be adjusted accordingly. If it's not the intended behavior, `start_course.sh` should be adjusted accordingly. Otherwise, I think the PR is ready to be approved (still need to do final testing).

@Rymik19 Let's stick with the current behavior. I'll make the changes in the `README` and approve the PR today or tomorrow.

@JHavstein I am sorry for the late reply. It is intended behavior, it can help with backing up course files by renaming them. Files can also be removed through UCloud UI before mounting the folder, so there should be no issue.

2025-01-28 14:49 UTC, JHavstein approved these changes

2025-01-28 14:50 UTC, merged